databases:
  - name: luxury cars lending
    databaseName: mysite
    user: mysite

services:
  - type: web
    name: luxury cars lending
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: luxury cars lending
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
